-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIZ+QcGO3ivw1QPEC
lH6Zew0n4diwWvCk4D8WXAnuNcigCgYIKoZIzj0DAQehRANCAAQ335G6ny4EoEXl
kTbIbPbIlOrCG6YjSqjO9a4q0Amr2WMveoPfocmtjDDGKyftJgnAVoMc2GjDyU0w
nMT0XtcV
-----END PRIVATE KEY-----