# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :create_app do
    # add actions here: https://docs.fastlane.tools/actions
    produce
  end
  
  
  desc "test"
  lane :tests do
    run_tests(scheme: "Qhapaq-Dev",
    devices: ["iPhone 13"])
  end
  
  
  lane :beta do
    api_key = app_store_connect_api_key(
        key_id: "QXVM6BLYXG",
        issuer_id: "ed489927-96f9-4106-8fe0-10f1479eae8a",
        key_filepath: "./AuthKey_QXVM6BLYXG.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    build_app(scheme: "Qhapaq-Dev")
    upload_to_testflight
  end
  
end


